import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";

export default function Home() {
  const [teeshotHover, setTeeshotHover] = useState();

  return (
    <div className={styles.container}>
      <Head>
        <title>FoundrMeet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to FoundrMeet 👋</h1>

        <p className={styles.description}>
          Choose a project below
        </p>

        <div className={styles.grid}>
          <a
            href="https://teeshot.fotura.co"
            target="empty"
            className={styles.card}
            onMouseOver={() => setTeeshotHover(true)}
            onMouseLeave={() => setTeeshotHover(false)}
          >
            {/* Teeshot */}
            <div>
              <img
                style={{
                  transform: teeshotHover && "translate(0, 0)",
                }}
                className={styles.img_shirt}
                src="/teeshot/shirt.png"
              />
              <img
                style={{
                  transform: teeshotHover && "translate(0, 0)",
                  opacity: teeshotHover ? 1 : 0,
                }}
                className={styles.img_shirt}
                src="/teeshot/shirt_blue.png"
              />
            </div>

            <div>
              <img
                style={{
                  transform: teeshotHover && "translate(0, 0)",
                }}
                className={styles.img_cube}
                src="/teeshot/cube.png"
              />
              <img
                style={{
                  transform: teeshotHover && "translate(0, 0)",
                  opacity: teeshotHover ? 1 : 0,
                }}
                className={styles.img_cube}
                src="/teeshot/cube_blue.png"
              />
            </div>

            <div>
              <img
                style={{
                  transform: teeshotHover && "translate(0, 0)",
                }}
                className={styles.img_donut}
                src="/teeshot/donut.png"
              />
              <img
                style={{
                  transform: teeshotHover && "translate(0, 0)",
                  opacity: teeshotHover ? 1 : 0,
                }}
                className={styles.img_donut}
                src="/teeshot/donut_blue.png"
              />
            </div>

            <h2>Teeshot &rarr;</h2>
            <p>CG visualisation tool for t-shirt designs.</p>
          </a>

          {/* Club */}
          <a
            href="./club.html"
            target="empty"
            className={styles.card}
          >
            <h2>Club &rarr;</h2>
            <p>Online club platform for communities that stick together.</p>
          </a>

          {/* Cardboard */}
          <a
            href="./club.html"
            target="empty"
            className={styles.card}
          >
            <h2>Cardboard &rarr;</h2>
            <p>Cloud storage for analog memories.</p>
          </a>
          
          {/* Start up profile*/}
          <a
            href="./club.html"
            target="empty"
            className={styles.card}
          >
            <h2>Startup Profile &rarr;</h2>
            <p>Showcase your Startup </p>
          </a>

          <a
            href="./club.html"
            target="empty"
            className={styles.card}
          >
            <h2>Community &rarr;</h2>
            <p>Discuss with like minded-people</p>
          </a>

          <a
            href="./club.html"
            target="empty"
            className={styles.card}
          >
            <h2>Freelancer &rarr;</h2>
            <p>Get your startup executed</p>
          </a>

          <a
            href="./club.html"
            target="empty"
            className={styles.card}
          >
            <h2>Events &rarr;</h2>
            <p>Explore the startup journey</p>
          </a>
          
          <a
            href="./club.html"
            target="empty"
            className={styles.card}
          >
            <h2>Benefits &rarr;</h2>
            <p>Avail exciting offers</p>
          </a>

          <a
            href="./club.html"
            target="empty"
            className={styles.card}
          >
            <h2>Learning &rarr;</h2>
            <p>Learn from leaders</p>
          </a>

          <a
            href="./club.html"
            target="empty"
            className={styles.card}
          >
            <h2>Services &rarr;</h2>
            <p>Get your things done</p>
          </a>
          
          
          

          
          
          
        </div>
      </main>

      <footer className={styles.footer}>
        {/* <Image
          //src="/fotura_logo.jpg"
          //alt="Fotura Logo"
          width={25}
          height={25}
        /> */}
        <div style={{ marginLeft: "10px" }}>
          Copyright © 2021 FoundrMeet, Inc. All rights reserved.
        </div>
      </footer>
    </div>
  );
}
